# Generated by Django 2.1.2 on 2018-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
    ]
