# Generated by Django 2.1.2 on 2018-11-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20181110_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='87000000000', max_length=14, verbose_name='Номер тел'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
        migrations.AddField(
            model_name='service',
            name='salon',
            field=models.ManyToManyField(to='service.Salon', verbose_name='Салон'),
        ),
    ]
