# Generated by Django 2.1.2 on 2018-11-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20181110_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
        migrations.AddField(
            model_name='salon',
            name='service',
            field=models.ManyToManyField(to='service.Service', verbose_name='Услуга'),
        ),
    ]
