# Generated by Django 2.1.2 on 2018-11-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_salon_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='master',
        ),
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='service.Salon', verbose_name='Салон'),
        ),
    ]
