# Generated by Django 2.1.2 on 2018-11-10 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20181110_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('state', models.IntegerField(choices=[(1, 'Не оплачен'), (2, 'Оплачен')], verbose_name='Статус')),
                ('type', models.IntegerField(choices=[(1, 'Новый заказ'), (2, 'Услуга оказан'), (3, 'Отменен')], default=2, verbose_name='Тип платежа')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_master', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
