# Generated by Django 2.1.2 on 2018-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20181110_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.IntegerField(choices=[(1, 'Не подтвержден'), (2, 'Подтвержден')], default=1, verbose_name='Статус'),
        ),
    ]
