# Generated by Django 2.1.2 on 2018-11-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20181110_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Master'),
        ),
    ]
