# Generated by Django 2.1.2 on 2018-11-10 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20181110_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
