# Generated by Django 2.1.2 on 2018-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20181110_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(to='service.Service', verbose_name='Услуга'),
        ),
    ]
