# Generated by Django 2.1.2 on 2018-11-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_auto_20181110_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='expirence',
            field=models.IntegerField(default=0, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
