# Generated by Django 2.1.2 on 2018-11-10 09:36

from django.db import migrations
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20181110_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='rating',
            field=service.models.IntegerRangeField(verbose_name='Рейтинг'),
        ),
    ]
