# Generated by Django 2.1.2 on 2018-11-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20181110_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='expirence',
            new_name='experience',
        ),
    ]
