# Generated by Django 2.1.2 on 2018-11-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20181110_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='service',
        ),
    ]
