# Generated by Django 2.1.2 on 2018-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_remove_salon_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(1, 'Новый заказ'), (2, 'Услуга оказан'), (3, 'Отменен')], default=1, verbose_name='Тип заказа'),
        ),
    ]
