# Generated by Django 2.1.2 on 2018-11-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_code',
            field=models.CharField(default='0000', max_length=4, verbose_name='Код'),
            preserve_default=False,
        ),
    ]
